services:
  weather-pipeline:
    image: ghcr.io/jeysel-dev/weather-pipeline:f7e3ba8
    container_name: weather-pipeline
    restart: "no"
    volumes:
      - /home/ubuntu/secrets:/app/secrets:ro
      - /home/ubuntu/app_weather/logs:/app/logs
    env_file:
      - /home/ubuntu/secrets/weather-analytics.env
    networks:
      - jeysel-network

networks:
  jeysel-network:
    external: true
