apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-analytics-staging
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: weather-analytics-staging.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-analytics
                port:
                  number: 8501
